language: cpp
sudo: true
dist: trusty


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - g++-7
            - clang-3.9
      env:
        - MATRIX_EVAL="CXX=clang++-3.9"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - g++-7
            - clang-4.0
      env:
        - MATRIX_EVAL="CXX=clang++-4.0"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7
            - clang-5.0
      env:
        - MATRIX_EVAL="CXX=clang++-5.0"

#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc && CXX=g++-7"


before_install:
  - wget http://prdownloads.sourceforge.net/scons/scons-3.0.0.tar.gz
  - tar -xzvf scons-3.0.0.tar.gz
  - chmod a+x $PWD/scons-3.0.0/script/scons
  - export PATH=$PWD/scons-3.0.0/script:$PATH
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir RapidCheckBuild
  - cd RapidCheckBuild && cmake ../RapidCheck && make

script:
  - scons test property_test
