language: cpp
sudo: true
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7
            - clang-5.0
      env:
        - MATRIX_EVAL="CXX=clang++-5.0"

#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc && CXX=g++-7"


before_install:
  - sudo aptitude -q update
  - sudo aptitude install -y texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-bibtex-extras
  - wget http://prdownloads.sourceforge.net/scons/scons-3.0.0.tar.gz
  - tar -xzvf scons-3.0.0.tar.gz
  - chmod a+x $PWD/scons-3.0.0/script/scons
  - export PATH=$PWD/scons-3.0.0/script:$PATH
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir RapidCheckBuild
  - pushd RapidCheckBuild && cmake ../RapidCheck && make && popd

script:
  - pushd src && scons && popd
  - pushd doc && scons && popd
