language: cpp
sudo: true
dist: trusty


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CXX=clang++-3.9"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CXX=clang++-4.0"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CXX=clang++-5.0"

#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc && CXX=g++-7"


before_install:
  - wget https://testpypi.python.org/packages/07/b5/a62e2884076bd96cb259f64eccb0fb0106f2b163977529ab416e4fc69a4a/scons-3.0.0.alpha.20170821.tar.gz#md5=c5242fa876ab0b3dc856ff90d110a5da
  - tar -xzvf scons-3.0.0.alpha.20170821.tar.gz
  - export PATH=$PWD/scons-3.0.0.alpha.20170821/script:$PATH
  - eval "${MATRIX_EVAL}"


script:
  - scons test
